# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
stringData:
  VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:lVr8E45zUHK6S68nlg9SbQoc,iv:2RgPwhO/qRVAsdPcwUKbyEZJprUgXcmfwWaroczRmag=,tag:HAhrbQXX4TBaQhztN2ePvg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZC9PRzhzTlBIV0ZLdkt6
        d0ZsWXNIbXlWSXYvZFRXeDNVV2c4aytIUUdzCndmYlAxMzdycERrL0t0dnBiRVFp
        eGltZ0xobm1HZFBQNWl2VmVtang3eVkKLS0tIFR0NWVTTWRFOEVzSzIxa1VHN20v
        T0VvZFl6Rk9tUUgwMzIwOUtXc24yUUEKhyulWrxgPNQSROKtnHR3q+HVgBMNRqjF
        RD+Rb/IoD/2fY81e4tVv3mlV/HB4h4lf8sewm5XbT24200H/aTcNSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T16:40:47Z"
  mac: ENC[AES256_GCM,data:i12CMdiTvyC1+HUroTzQvRfgWH0brlaU0NI8ONFnFM2YVHC10NsuoiyQP2frdHcqRb/iVPJcwiZkyUYwRcCTS3cq1J9Qt1Hi5tt9oDyfCDJtu7vwMrP+T0MTaScP4HxiuLjIgNHe9taQPZBYMLOzZU71dPFciW+qqF2Nq9OUXxo=,iv:YhKPPVBrax1ND0MNRdahhYpmD0aTsDq5WENnFIzlozU=,tag:KmyoGgLjXtv/i+WoVbk6DA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
