# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:3RoE3PcsfHZEuz+MzoAmpYGhtcy7sgviLR4EL8SlzJM=,iv:RUutyoigAI5oOJU8YOzrpancp8phEAxLtnqdpRuE4fI=,tag:BfWQnOls9RHAoKB7C4rSgA==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRWVLUVZvbEF6ZTM4Nkxl
        eEV0SGNYL3lLbUdoU3J4Z3lQOXBFVCtIc0I4ClhwcmZHUW84djZiREE0b3FyQkxZ
        MkovZWJRUTVaSGk1NUVWR1krcDNsRncKLS0tIGcrQmE2WEw5N0IrUzZLQld5MEta
        Yk40N3U3cDJmTnZlRnM4SHBsNUxGVTAKFWAMG5gVaOXqj/EiPC1XCRwQcCXZAZyF
        OfsOGK0tdRstRRgrDGPV5yKIKqtB/9K74i+CDieTp1N8V1Fjdfa4kA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T20:27:43Z"
  mac: ENC[AES256_GCM,data:5TPKU9+GdZMUFnfGkVD0BGbc9EIYx2aNKvHOqstp7G5bUrW3gLrJ6ZSdLsh4yhrv4mYSWUE4CsD2eXbl3x4s4qAACx48Y31WfDI5tj1a5AHMX+Q85ZBOTuXtj1R+JnwxXrH/bX1o24wVuyjIqY0xD/UtFAy5SSMbCfI0zaiM6CQ=,iv:vE4+EMD6NrM5djTVyVSNy4guvy2V/0uV4JtSQ0nHAQQ=,tag:lJMYuv+C2pHz+jz+5ROKKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
