---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-java
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  dependsOn: []
  values:
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java21@sha256:74ae85d0224f7bffbf47ff1286785b91f04690b672e1c36431bf7d0a50679f51
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 2000m
        memory: 8Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-java
    livenessProbe:
      initialDelaySeconds: 30
    readinessProbe:
      initialDelaySeconds: 30
    startupProbe:
      enabled: true
    extraEnv:
      TZ: America/New_York
      ENABLE_ROLLING_LOGS: true
      MEMORY: ""
    serviceAnnotations:
      lbipam.cilium.io/ips: "10.13.17.50"
      external-dns.alpha.kubernetes.io/hostname: "minecraft.${SECRET_DOMAIN}"
    minecraftServer:
      eula: true
      difficulty: normal
      type: VANILLA
      mode: survival
      pvp: true
      motd: "coopernettis super cluster mega block world simulator"
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      serverName: "jingleJANGLE"
      serviceType: LoadBalancer
      servicePort: 25565
      rcon:
        enabled: true
        serviceType: ClusterIP
  valuesFrom:
    - kind: Secret
      name: minecraft-java-rcon
      valuesKey: RCON_PASSWORD
      targetPath: minecraftServer.rcon.password