apiVersion: v1
kind: Pod
metadata:
  name: minecraft-java-migrate
  namespace: games
spec:
  restartPolicy: Never
  containers:
    - name: helper
      image: alpine:3.23
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: world
          mountPath: /data
  volumes:
    - name: world
      persistentVolumeClaim:
        claimName: minecraft-java