# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minecraft-java-rcon
  namespace: games
stringData:
  RCON_PASSWORD: ENC[AES256_GCM,data:aUmlIJ+yqQKdqmVJFmyk7JCnRg==,iv:aIoGE4csCJ1CJpPTPXVrCWOchAqsPvMyV0Ah+MoGu2U=,tag:1MKGzYj8e9YKyhyRib1Y2g==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bU1lc25mQWpFYlpPczB2
        VC9aWlA5TENzOXM3TDYvalpGemVISThOU1dZCnVubmZUbjgxK0N2WUp4K2JlNUI3
        cm8rT2RhaG9IRi9oMUF3RjlYR0dzMWsKLS0tIHZuMG5IaVBLK25kQ2FjV2NoT3VM
        bE9BQnRIRlZMU1VubU5QNHpyQkNQWG8KFnygbW+rp3yH8SFj9yxZha+/eXwR2Zz7
        6cI6U85HEtU6UOPkEm9KdG2GoYnOU+MdYTSm8flFivb/xXCFnUduCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T18:08:53Z"
  mac: ENC[AES256_GCM,data:iAAxPxL19whXv5KCGNPayHHuJHPOfmIGIszwiAxxeSjIyma4m8wqImuRMOq9KQpFDdYExwJqbDOSvwSuJ4mTnNd4HUtqGv0JXqTgHIz5gzqSo71Rf/8ShwEhlmBErVLqVbbqGeHJ1a9AvVzQpbHsrcMcOs4hBWa8O6HbmThew0A=,iv:Gi78fGei9NeAHbrtNnEjBB1iyFaaI9Q9Zfds+LqIBGA=,tag:Da2g/PAP/5DOvl+L9dnQRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
