# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:TNecutAcaGrIKN+EXhtaUkw=,iv:Vvg4+4Xy58Q+zqtO5+DPNs4kTSmk7E+GIzRNzjqtqZ8=,tag:U2rnSzOyeeauAvrGAWQ0MQ==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVWJkKzNDMWdieUlLbTB5
        UTVXZjQydnBUTjBtcG1CSkxZRjFZNEFMMFY4ClR3OWNGcUl5bjhYSUN2bFkxS0JM
        dE14QlpJa2NpYm1VVURPQzhCVE9MdlkKLS0tIEhIZnpPTVlKaGJXVFZ5Rm9ZTlha
        eHg3VS9CMGY2UFZKc2xUaWt1alNjN3MKeKDyNpBdy2l5AoXNDZ4ZVdqmFKnbiHJi
        JFgsXXXkwfDtEZRVMijQVgJbmMKORszVYiJjfoP1LFXtqaKUH+PuOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T03:42:01Z"
  mac: ENC[AES256_GCM,data:7PTpKnZfUPFJ4qsYoUa39sjl53cYdhuUHNwobl7Z13bgeqpvXgAZ5qN3ECcsfHl/g8/TSQimmQqUI6rK6Q+rT6W+qlcleVKVkqB2HQWkAzBbfcpOV+OD8pERaXV/LgRENHuuVgbwww3I4/aoAeGDf9rRbk5Se/hFaJytdR/YTKY=,iv:uUSgZqrGF/etgGugGd8Rt6PS5/kXBz1nKWymeuI4968=,tag:Cl3MRG3G3QyucHCqm0h0dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
