---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vpn",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.87",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "10.13.87.1" }
            ]
          }
        }
      ]
    }