# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
type: Opaque
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:J231/WfRiDvaWfo=,iv:J1NBFP9iX4KJf1FXWbNSoPd+GMCZisiSloUUqBmv03Q=,tag:whIBMrIZddCbO5uue8clrg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:j3MpFj5b5N0073M0Kk2Din7dJhBjWQ4W,iv:GZjRPC73oGPqckkI9eWHBaITUk+Dg6/QIJTLalqdSUE=,tag:NSH2d5lb+O259suZDb8ytg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Nx5XzMP8PlbLo2qqAuos,iv:F1qENnkm7sAtDigQ+e3MK7Th3vOCPvHM3VyD/80dULs=,tag:c5u2sh0zghNPEQj7RiI1bg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdlJQL3ZSSHVKVE5wWjBK
        ZzVnZHlIWEVLd2JlbU83TjBxVVVMdmZ2NTFNCmpSRHROMS9ZV0NjOExMaTNvbnNs
        RXNBYlc1WEUxU01TV1VLUGJHTEtHcXcKLS0tIHd4VlZVMDc4Ukd3c1NNb21NOFB1
        eFFBVEN0enk2cTNzQldGbjVvb1BmbEEK4yhe4/IRqONBgISiTwqXRaQhA2cGl6tV
        Ro86cN8KE4xKe2sVYDpqtYIRbJGDRUYLLyl8tyjh9q3hrJp4XaFnMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T17:11:18Z"
  mac: ENC[AES256_GCM,data:Sqz5D0P02MOW8kODTrTFhmllI4Uk+3MoWXsV5fEetLD/Bd+t6mvaLq6ipCSF3qU3B9APC17kp7c1g6fNuii3Gahc61cvrcM/lTj41QXp8PSvoGXbRL5PhS8/S7O7Lawoy++vuTEVp8OZguvBwUFWNCPtEVujS9t8FeCFC58RMLw=,iv:RlvONlaskkLcLTb2aUD7JGVxYqRv9/vVaurGyIwEvMY=,tag:HWY99iT6uGR/MFqkg9mltg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
