# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Rvp9rbGKzIDsukCnsYIfyA==,iv:w/ZzmJ9LRaO0sP+bpxjtncYohhiImtDRjCAaWBKBh0A=,tag:1HMfI/s6LskUIIhJHAeavA==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbXJCcHZibnpyVEJaUkp6
        a0FheHpiRG56c3ZNclhqNm5nSjRhSk8xMEVzCk1ZRG9neTVOTk1xR1JsOUpGM0Qv
        b1lZVld6T1JpMDZlRzFFMGtpM3hzVkkKLS0tIHlmTTNNcDNvRW9DSFZRWURadzBm
        dXhXQXRFKy95Qkt5R1paMFBqVnNPc1EKyjiYfsZZC33f7Am5oNH4FbFmTnBuEnst
        my7uudYQScVdQ3ejeHIi2fiuj/KbPFzu7gfzLeQKr42kLQq4YoqNLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T13:38:52Z"
  mac: ENC[AES256_GCM,data:kUP9mV51N1wa5HC3kMmoIErWnYsoVb6cH9fpEwQl14g+ubayVwN6KX2WYraoQLaF8NeHKwRQWADXioCUbei6OeMPCiJppW9tfEAZEJqfw04zknafl4DFCHnQaOdQcIrMjrML3SHDklcUJ+yn8elJkNkXwxHO87ggYHKY4CjIKEE=,iv:NyqLjJI26DwzBPRIaMRvCv0cCg9EvKMLuqHknLxrmdY=,tag:SczXeQMlBHUEL5fiYWmJlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
