---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./echo/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./seerr/ks.yaml
  - ./thelounge/ks.yaml
  - ./autobrr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./trilium/ks.yaml
  - ./vikunja/ks.yaml
  - ./n8n/ks.yaml
  - ./stress/ks.yaml
  - ./agregarr/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./atuin/ks.yaml
