---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs-system

components:
  # - ../../components/alerts #alerts not fully implemented yet.

resources:
  - ./namespace.yaml
  - ./openebs/ks.yaml