# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: seerr-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:BNik2wbHWSUlX0yomzfS3S3gL1+ULJF714K2VIn6mqpFXwoD2woWDl+pP78btIbLcSDTTddz9XCKq5AhTkDyzncxHjM=,iv:mHKGAbqwirj2x8Hjg19inmxQgonMNbLrcMSKphd3FMk=,tag:ELOIGXNOq16ML6N4PgdOdg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVEhLdFhsM210K0lpeFRV
        T1lScDljWnFtR25kNkY0Qm5DRGtOcThtRG5RCnB0YTFRaGFxS2puVDJVWjVhVFk5
        OWd4VEpKKzRLYThmclVYMHRvdVEwUzAKLS0tIGZvOXNLQXlLNUFjRjBNZ1l1K2Fq
        aDByMzQwY0Rra2d0dkVoaUxLQVE5SHcKBE36R6FuLcrBJfP54WD5F1Vf8bMWZeGZ
        QxZ11qzGHEoqbOefMW+zf7JpLVAfCVRFBa2ulG0vZpzxyMh9pyULDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T02:13:53Z"
  mac: ENC[AES256_GCM,data:OVrniQynRj5TeLwm1jRdf1xXlPgB7SYxT1X3/mahq8pr538u1TzSxN/842YumcmUuHzI+0+wdit/sLFb4rz2X5qj8DnKuTthocrDTRasfbN4ZzRRyeO2efsqzqpmUumDFnl8OUuHlChX5hvAvwdKX/XUYWzRvKXdaukBVMvLPV4=,iv:Uq5srMmcgqWPxrfeGeY/RsrIZfRE+c5+MAcZsff6hwQ=,tag:P1ZA7nAocwBJqIAJcdAIQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
