# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
  namespace: volsync
type: Opaque
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:+qTyua7f3wnaFsM=,iv:UALyg2iRN9AjLC9dtuSZCAkaK9OUj3fykGEaVMcqkzw=,tag:3CIldkjutxu6uZ+bxrEWFg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:5TPFUY/tAQpeMHaEKeOKRn6xpYJRp7oW,iv:pP7am089uZBJXbtN+N2Vno4vHaMsi8oJVllQkVXVCFM=,tag:xTYz5i7+QFdX3PQSuAg0dw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:/+S0jO79synKnuwjdRGY,iv:cRm4laD4mCS3/WHi5MS2QdhpoMDBRV98WmNwKqRsAi8=,tag:w/B7/NzlvY6yeY+FvsGAxg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRVBPL0pLQzkvZ1FZQzVy
        bEZCTUo3ZzkxOWhhN1F4YmlHR1FqYzlJblFnCnAzUjlVTkNLS0djMWN5cDE2T0Vx
        Qi9JMjg5emdyRGF5M3luQ1lkbE1OZjQKLS0tIHB3VzFiS01BVUxCN1BHTXBpcUVa
        RmZnVVc3WEw4MjJzNmxyQkxuZW1RRWcKGIM0YQI/OuzpSaOZyJu2SilAwcuvPxon
        7GbK7N/wnpP0xT4Mth0Sxe8cYBmYjAhgoRrsf1ifer1rEKbMC623Nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:41:59Z"
  mac: ENC[AES256_GCM,data:+Gw+3g8FTs28F0OxWyIYoKdqOAs8omdWEL1H6ZRI7fzHiL9C+IKk9AC3fGALYEPoomYV/h5oAIleHV/EVPVM6qV4j6rWotq9bGO5JuzpKoyRtHBxVxIXSBIncx2u6QOB8Gz+nBBjNnzkskc2x5pcmgBdM+vy8VVyYF5V3Qw64cY=,iv:yz4xJYtyfOgvireVa+9XH8etF33FTRBjaM4lElyLJqc=,tag:ZjjYNNjLiF30CnvvY/ZdnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
