# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
  namespace: volsync
type: Opaque
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:E1ssq50EZ3fpErE=,iv:RSrpqHTcNhsvfWBY2LS4Mv/Y8DHA3zVW31ORuxN9ooo=,tag:F75hdJ0XBPRvKM3+0ukEbw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:8dW6G8/jbbq23uxYz8WaOKiKcrRLKLg7,iv:ilXG029Dw1b4OZuGGanHvr3yZhIF9MGv7FRlbJFWBnw=,tag:SYtxBAvkaEib5KK5NVrTdw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:eCMTKkTYq5Fy1er45HZb,iv:G5evAOav5q7NkEv2ByQXZNOBmtjhhlS+gkys0NW9oUU=,tag:zI3bcVhPbGFwb3ETpDgTPA==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROVZtR2NlMFdDL3hUbEYr
        ME0xeWRBbkQzR2RGT1lPSHErc0t0d0VYOVU4CjFhOVpWblpwMkYvRmd2cGpqbEho
        ajd4SjJVcnJjR3lUbEJYOC9hdjg0R1EKLS0tIFI5YlBWSnhmeUVUeXJMbTJ4cE1Y
        c3haQlZsT0J6SW1nL2JVVlliK2kyeUEKwWJe8zhALHXmSa6cAXa5R6aF/AduEUXK
        vFHQU4lGLHLB45JUE/tS61+b8/78lPod673JJvzhfiztKSzru1X6yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T18:48:12Z"
  mac: ENC[AES256_GCM,data:TGrA2Wb/tN9HQi8USH91nj82VYQPdgVB2dmhJswbF86kMBtcF9vUmon/LILc19w7TjR3C5hgAWzMGonUzWN/TnhUajXHgTN/6QvxtxjnciCzXSbO+eWlEzN8xBjL9p9jTsTk2He1DvoG5d8ZmQJ5eDx5FjUv6KmwEGFllBQ+1iE=,iv:hWosIjhi/xr9oQWizrKg6Xf7pR09kr4qGrfpUN7HXWk=,tag:sr6UuzB7ausolPX96wghmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
