# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:YFsoZgxCWHjANOX9uUtSE4tYlnKQH3c68/PFALHq5Iw=,iv:zSveknnavQwwK0fv/3DMEk8hRgVVYnclkwyAb7gdNgc=,tag:jCYxnduBpziGH5ZveQ43Iw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONlBMMmJ6eGQ4R3JjWEZ3
        b1NSTTI5ZVVwRnJWSkFCYitFdWVIMlhUZzNVCmwxMXlrTmxzaXRLTTJZRTJiSFAr
        S1hwUUQ5aURmTE5KS2J1ZjRKZzY1b0EKLS0tIHI3ODJsRmpwNVVZbnBvWTFRd1RN
        Z1lhSzhCWitiNnpnbGd5N0RwNk5hbE0KE565glA8M9oDrLgXnne4RRk564QCK/Cb
        EWarZKQAW/L0tTr0VN6qm8DP2rrE/7dMLR3ze6593nHK0paxfQFUXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T00:21:04Z"
  mac: ENC[AES256_GCM,data:PbArW5A2NFX97ZY2M6lxlxQGKS2gCj8HJLOkCA+u6UttJ5veptXH4qfk5xzg6aRWDDWCW8sT+VECqP5KT8xL+jvh7sPjEEiaVNxfO9qCEHQRFfFKlirDvZIqvlphpJphkLLD0xWlPzZulHkMunmOglHW/S1xoHdUV2470RRpG3A=,iv:t4EDeRTlzZM+BSd3SroMyVqMXbno2iBiLhG+B8EeMLM=,tag:pXkoxmcTg56n80U9zzA9nQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
