# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:BXYBvfX4nQMWnVz356vPBLUUfw==,iv:7JsAgCNnwSFnqUrcGZK+fzPxgNvJaTzTtwyX9y99Lz8=,tag:JakokKQDL6dJj13X4+wP6g==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeGNPaGNkSVJ2a1hSZW02
        ZTJpUXVzUzQ5REROSVVKaVhVMS8wMGd0aERrCnpCemhXdnhMckloSXYvYm5JeUJ3
        Q0MrTXNiOHF2REVzV2tRU0dQUi95Y2MKLS0tIDdrNERCZUZITWhvbmo3elZVOE1r
        TzRkRXVZWnZyTCtwZi9rNHk3eWUyZWMKi6MjguX9ZThA+tfUDbHUGE/i4RSAP5y5
        fI80dJzmd2KVdbRn9q4bv4oK5JosqZrxgL0+bBS/jgVG++zYKJ2mZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T21:26:28Z"
  mac: ENC[AES256_GCM,data:8X5vQB2Az6AojDVlb/s0ljIKvo+wNBU7DZkKbx7dxYNfAu0ihfVxeG1nIkeqPjjr0LESTQ8s4SfOgq9lEv5/TRrmbV/R2lkifY5dM3atqGnEL/UarjyISXeb8JRliq2BwrEgwniNuSHeJIUuckvBnVaVdqdqay68fYAnulm8XbI=,iv:xNG3CAv5AkzopGPEUG0R6GXZHL7XFzoPCIxTdHNnC80=,tag:Qt829lXj0ayTziY53Y7XRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
