# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:2I+2STZOzN/sRt45cM3N64sOKxnTm73M34rFxvmWn1c=,iv:ZVURQ0ZwF67dQe7uwRTvOBcGQ0eIyL9a8w8eJg6ttlA=,tag:OGtcOoumJ2y1EjiQYs3krw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT0NwL3FMeW9zRUhwM1l2
        a2RTOEd5bGpNY1ZHVnh6bjQ1ZFkyeW01eGdrCkEva2JYcXN2dVhUb3phSWlEdGFs
        Z3pkcTFhdXIxVDJzRVBaVHovbGR1d2cKLS0tIFN2Qk9YYTBhdmxYVWFNQUhMeU1K
        cDBhVzMxZHRyYlVRTUNXdyt1bWNVZUUKmMTTS9nykl7VbNLhv6fhuoIeFQEpS9F9
        bZyy1kwfrJVr0YMqoah4K2zXS7ijgdm6GAJBWruF80nDqhAhYEmADw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T00:53:34Z"
  mac: ENC[AES256_GCM,data:C/vQxLIrAwoHIDFMlG/cTB7qjUga05QaN2HvNMk2ljHoiEiDpgJYXOwqdEDA6S9sKzK7b+9xvAFC8eA7/rj9YIP0L1shlitzaFKq8C5LRgzc/zWTSL8rWfbV6onwvjDV4iSQwFPIkBHgc/EhiIzd3VslgrfLf/vKCId/+tWyqc0=,iv:b3mJOQhVkYHbR9eDCoT07fY+BGJ3ActgrdOV06simOA=,tag:jPMbKqnL4icBZtF2s8Szqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
