apiVersion: v1
kind: Pod
metadata:
  name: vpn-test
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "vpn",
          "namespace": "kube-system",
          "ips": ["10.13.87.50/24"]
        }
      ]
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]