# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
  namespace: volsync-system
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Myy4/bOVCGugroNFCxy5,iv:+Bdi7TYiSp2O0ZFL1THPdunVi89u0LU2yJyB68yhPSs=,tag:S5nKs36+BNBWjHvhIHrO5A==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSnBQTUdKVDlQSFEwYlho
        VWlEa2YzUWMyN0lKQkVkS0ZxVWlCemJ5clc0CkwvTmYwSmJpc3hSMy9wUVhIdWwx
        YzVRSnFSYTRVMGR2RjJVNW5pKzVZNXMKLS0tIFV0TG5TV1F1UnRxVWVzdEcrYzhy
        L01vRzl0NHVycmlUbUpLdmRwL3FndEEKECPFkoZPqPC+lHL4GY+6WVQLRYbruxq/
        rj4t5jK+PVYA2/oi5KXYKGTFRdLu+t/kD9u0UXE4MYkvwNP2pfu7jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:23:16Z"
  mac: ENC[AES256_GCM,data:cLJyMIuLp/qtys3Y5O5IawDIbYyqoaXiYzBgInK3PpxGfrSLQV9560en69p6HNx2etxqTIh3FJjIHpxskdm6WgBE3bu0kcpBs58aOQfeKVO44tlsXlNA3dSZi787vM4pheN915dFEAJnKQ3DeccuJXghuCio5NGL1BjVCMTqRms=,iv:WZrAzqkpA3f1uvm+f0UFRiqKyjjOfPE9kN0ZWRl3EXM=,tag:vEb5dLXmkgdCTkII4odLLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
