# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:y09V8Sjl8C1vRWb/1SjGJkVmkFo2MUQilqZPhfRn4PA=,iv:Nf93MNhXLYyEKEpPzvd9SZOg1b6Y2weukV8+uvKP9ws=,tag:+8+ouGmJX984V7v4sfLdjQ==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:R3sBITFpOuScrqKdiJc4UAOX/3a6Ph69XFYKiWldR8A=,iv:FOEzkjOw5MnUWfns6YA5Q+oai0Mr6QjruoQKf7gACN8=,tag:UUY8DxNK12CkbCgSs1BNiw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL01CMVo3REdkOTZoYUhK
        NWt0RzhSVHRDbWdjYURpc0RsRjRWRHNldzBVCmZnVTFlWTk0RDA5ZnJOYWVYRUxG
        S0M2RURCWE8wZ3JDdmNxQktoUjk2TzgKLS0tIHVPRytXdWoxa3hQczhmTlo0OE1Z
        andoT1hqd0FzWXdUYkw2THB5bzhwWDAKNA2M4Kf6176E1O95Nmu54XZPjzOA6B0V
        CTl0KeVgCZ0bytAneqNAtD7iBF8vM53A10ohnIRJoZCru8Y+9c8yOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T15:09:40Z"
  mac: ENC[AES256_GCM,data:4rtVTIunqzOuT7Z1nM7Uxm+4x+QO13Lwe+cSxFpMJ/IHFSgKS0cMukIbIXN4I3+DnWti9fX9b77ngPGM8TgKUK9FUnI/SJhkF48OVrjPNQLW6NKrXJldr1T0xWEhV/LRA5FdNQOX3f2KsnWoaxE3/tUdEH//ZyPxoAlBF2cL/0w=,iv:722iWBEWfBacE215zrFeVSTyRRfGfh9yNI181KChbKQ=,tag:yXwpZou+UgGKOUrZF1CvAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
